#!/bin/bash
# ─────────────────────────────────────────────────────────────────────
# lib/env_seed.sh — first-install .env seeding (AWS-vs-.env-only).
#
# Source from mobius_install.sh:    . "${LIB_DIR}/env_seed.sh"
#
# Exports:
#   - mobius_env_seed__for_component <ID> <project_dir>
#       Idempotent. If <project_dir>/.env exists, leaves it alone.
#       Otherwise prompts ONCE for AWS-vs-.env-only mode (30s timeout
#       defaults to .env-only). Honors <ID>_USE_AWS_SECRETS pre-set
#       env var to skip the prompt entirely. Persists answer to .env.
#
# Generated .env in AWS mode:
#       <ID>_USE_AWS_SECRETS=true
#       <ID>_AWS_PROFILE=${<ID>_AWS_PROFILE:-}
#       <ID>_AWS_SECRET_NAMES=${<ID>_AWS_SECRET_NAMES:-}
#
# Generated .env in .env-only mode:
#       <ID>_USE_AWS_SECRETS=false
#       <ID>_POSTGRES_PASSWORD=<random64>
#       <ID>_SECRET_KEY=<random64>
#       <ID>_API_TOKEN=<random64>
#
# Extracted from TILES install.sh:tiles_install__seed_env_if_absent.
# Generalized to take a project ID so the same lib serves TILES, NVR,
# SMART_HOME, etc. The component's own start_utils.sh resolves the
# project-specific vars via bash indirection (MSG-303 contract).
# ─────────────────────────────────────────────────────────────────────

[[ -n "${_MOBIUS_ENV_SEED_SOURCED:-}" ]] && return 0 2>/dev/null
_MOBIUS_ENV_SEED_SOURCED=1

if [[ -n "${LIB_DIR:-}" && -f "${LIB_DIR}/log.sh" ]]; then
    # shellcheck disable=SC1091
    . "${LIB_DIR}/log.sh"
fi

_mobius_env_seed__random64() {
    # 64-char hex (32 bytes of randomness). Fall back to /dev/urandom if openssl
    # isn't installed (the bootstrap step usually ensures it via curl→openssl
    # transitively, but defensive).
    openssl rand -hex 32 2>/dev/null \
        || head -c 64 /dev/urandom | base64 | tr -d '/+=' | head -c 64
}

mobius_env_seed__for_component() {
    # $1 = component ID (TILES, NVR, SMART_HOME, …)
    # $2 = project directory (where .env lands)
    local id="$1" dir="$2"
    local envf="${dir}/.env"

    if [ -f "$envf" ]; then
        mobius_log__ok "Existing .env at ${envf} — leaving in place"
        return 0
    fi

    # Indirection: read ${ID}_USE_AWS_SECRETS via the var-name dance so callers
    # can pre-set the answer.
    local pre_set_var="${id}_USE_AWS_SECRETS"
    local pre_set_val="${!pre_set_var:-}"

    local use_aws="no"
    if [ "$pre_set_val" = "true" ]; then
        use_aws="yes"
    elif : >/dev/tty 2>/dev/null; then
        echo "" >/dev/tty
        echo -e "${BOLD:-}${id} needs configuration:${NC:-}" >/dev/tty
        echo -e "  ${CYAN:-}AWS Secrets Manager${NC:-} — pulls ${id}_POSTGRES_PASSWORD / SECRET_KEY /" >/dev/tty
        echo -e "    other credentials from named AWS secrets. Requires aws CLI configured." >/dev/tty
        echo -e "  ${CYAN:-}.env-only${NC:-} (default) — generates random secrets locally; no AWS." >/dev/tty
        echo "" >/dev/tty
        local answer=""
        read -t 30 -r -p "Use AWS Secrets Manager? (yes/no, 30s timeout = no): " answer </dev/tty 2>/dev/tty || true
        [[ "$answer" =~ ^(yes|YES|y|Y)$ ]] && use_aws="yes"
    fi

    local profile_var="${id}_AWS_PROFILE" secrets_var="${id}_AWS_SECRET_NAMES"
    if [ "$use_aws" = "yes" ]; then
        cat > "$envf" <<-ENV
		# Generated by mobius_install.sh (AWS Secrets Manager mode)
		# Required before deploy.sh: set ${id}_AWS_PROFILE and
		# ${id}_AWS_SECRET_NAMES (space-separated list of secret IDs).
		${id}_USE_AWS_SECRETS=true
		${id}_AWS_PROFILE=${!profile_var:-}
		${id}_AWS_SECRET_NAMES=${!secrets_var:-}
		ENV
        chmod 600 "$envf"
        mobius_log__ok "AWS-mode .env stub: ${envf}"
    else
        local pg sk tok
        pg="$(_mobius_env_seed__random64)"
        sk="$(_mobius_env_seed__random64)"
        tok="$(_mobius_env_seed__random64)"
        cat > "$envf" <<-ENV
		# Generated by mobius_install.sh (.env-only mode, unattended-safe defaults)
		${id}_USE_AWS_SECRETS=false
		${id}_POSTGRES_PASSWORD=${pg}
		${id}_SECRET_KEY=${sk}
		${id}_API_TOKEN=${tok}
		${id}_FLASK_ENV=production
		ENV
        chmod 600 "$envf"
        mobius_log__ok ".env seeded (.env-only mode, random secrets): ${envf}"
    fi
}
